language: python

sudo: false

branches:
    only:
        - master
        - develop
        - /v[0-9].+/

env:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="lua 5.3"

os: linux

addons:
    apt:
        packages:
            - libreadline-dev  # needed for Lua itself

before_install:
    - pip install hererocks
    - hererocks env --$LUA -rlatest
    - source env/bin/activate
    - if [[ "$TRAVIS_TAG" = "" ]]; then luarocks install busted; fi

install:
    # test that it builds; "source"ing is required because the $ROCKSPEC
    # variable is exported; not in "travis-stuff/" because it is run on my
    # local computers also
    - source ./build

script:
    # test that it works correctly
    - if [[ "$TRAVIS_TAG" = "" ]]; then ./tests/test.lua -o TAP; fi

after_success:
    - export DEPLOY=true
    - if [[ $CC != gcc ]]; then export DEPLOY=false; fi
    - if [[ $TRAVIS_OS_NAME != linux ]]; then export DEPLOY=false; fi
    - if [[ $LUA_VERSION != "5.3" ]]; then export DEPLOY=false; fi

before_deploy:
    # upload requires a JSON library
    - luarocks install lua-cjson

deploy:
    provider: script
    # need to skip cleanup because of changes to rockspec in "install" step
    skip_cleanup: true
    on:
        tags: true
        condition: $DEPLOY = true
    # for security reasons, LUAROCKS_API_KEY is specified in repository settings
    script: ./.travis-deploy
