#!/bin/bash

set -e

sed "s/##__VERSION__##/$VERSION/" matchext.rockspec > "$ROCKSPEC"

if [[ "$TRAVIS_TAG" = "" ]]; then
    luarocks make "$ROCKSPEC"
fi

if [[ "$TRAVIS" != "true" ]]; then
    rm "$ROCKSPEC"
fi
