#!/bin/bash

set -ev

VERSION="$(cat VERSION)"

export ROCKSPEC="matchext-$VERSION.rockspec"

sed "s/##__VERSION__##/$VERSION/" matchext.rockspec > "$ROCKSPEC"

luarocks make "$ROCKSPEC"

if [[ "$TRAVIS" != "true" ]]; then
    rm "$ROCKSPEC"
fi
