/*
 * constant.h
 *
 * Copyright 2017 Jonathan Goble <jcgoble3@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/******************************************************************
 * Do not edit this file directly! Edit constant.lua and then run *
 * genconst.lua to regenerate this file.                          *
 ******************************************************************/

#define LMATCH_OP_FAILURE 1
#define LMATCH_OP_SUCCESS 2
#define LMATCH_OP_ANY 3
#define LMATCH_OP_LITERAL 4
#define LMATCH_OP_NOTLITERAL 5
#define LMATCH_OP_CATEGORY 6
#define LMATCH_OP_RANGE 7
#define LMATCH_OP_NOTRANGE 8
#define LMATCH_OP_SET 9
#define LMATCH_OP_FRONTIER 10
#define LMATCH_OP_BALANCE 11
#define LMATCH_OP_AT 12
#define LMATCH_OP_CAPTURE 13
#define LMATCH_OP_ENDCAPTURE 14
#define LMATCH_OP_CAPTUREPOS 15
#define LMATCH_OP_BACKREFERENCE 16
#define LMATCH_OP_SINGLEREPEAT 17
#define LMATCH_OP_SINGLELAZY 18
#define LMATCH_OP_SINGLEPOSSESSIVE 19
#define LMATCH_OP_GROUPREPEAT 20
#define LMATCH_OP_GROUPLAZY 21
#define LMATCH_OP_GROUPPOSSESSIVE 22
#define LMATCH_OP_BRANCH 23
#define LMATCH_OP_JUMP 24
#define LMATCH_CATEGORY_LETTER 25
#define LMATCH_CATEGORY_CONTROL 26
#define LMATCH_CATEGORY_DIGIT 27
#define LMATCH_CATEGORY_PRINTABLE 28
#define LMATCH_CATEGORY_LOWERCASE 29
#define LMATCH_CATEGORY_PUNCTUATION 30
#define LMATCH_CATEGORY_SPACE 31
#define LMATCH_CATEGORY_UPPERCASE 32
#define LMATCH_CATEGORY_ALPHANUMERIC 33
#define LMATCH_CATEGORY_HEXADECIMAL 34
#define LMATCH_AT_STARTSTRING 35
#define LMATCH_AT_ENDSTRING 36
#define LMATCH_AT_STARTLINE 37
#define LMATCH_AT_ENDLINE 38
#define LMATCH_NOESCAPE -1
#define LMATCH_ENDOFSTRING -2
